### PR TITLE
Update FuseSoC to 1.9.3

### PR DESCRIPTION
**Pull request by olofk**
Also cleans up the installation commands a bit

### CODE REVIEW

**Review by Nancy-Chauhan — APPROVED** [review]

**Comment by Nancy-Chauhan** [comment]
Thank you for the changes @olofk, do you see the scope of any further improvements which you can help me with?

**Comment by stffrdhrn** [comment]
Ping @oleg-nenashev, any plans to update these versions?

**Comment by oleg-nenashev** [comment]
Oops, I have completely missed this PR

**Comment by oleg-nenashev** [comment]
Automatic build is still in place

**Comment by oleg-nenashev** [comment]
So DockerHub needs to be reconfigured to restore automatic builds.
There needs to be an automation bot going forward.

There is https://github.com/librecores-ci-bot which could be mirrored to
DockerHub.

**Pull request merged**
